# These are supported funding model platforms

github: [gabrielrpopa,  frankcberardi]
patreon: gabrielrpopa
open_collective: gabrielrpopa
ko_fi: gabrielrpopa
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: ['http://infinite-loop.ca/']
